# Generated by Django 4.0.4 on 2022-06-07 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=75)),
                ('password', models.CharField(max_length=50)),
                ('identidad', models.CharField(blank=True, max_length=600, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('resultado', models.CharField(blank=True, max_length=500, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10)),
                ('sexo', models.IntegerField(blank=True, choices=[(1, 'Femenino'), (2, 'Masculino')], null=True)),
                ('Peso', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('diabetes', models.IntegerField(blank=True, choices=[(1, 'Si'), (0, 'No')], null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('colesterol_total', models.IntegerField(blank=True, null=True)),
                ('hdl', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ldl', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('triglicerios', models.IntegerField(blank=True, null=True)),
                ('tabaquismo', models.IntegerField(blank=True, choices=[(1, 'Si'), (0, 'No')], null=True)),
                ('antecedentes', models.IntegerField(blank=True, choices=[(1, 'Si'), (0, 'No')], null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
